import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function formatDate(ddmmyyyy) {
    const [d, m, y] = ddmmyyyy.split("-");
    return `${d}.${m}.${y}`;
}
export default function BookingSummary({ room, plan, searchParams }) {
    const photo = room.photos.sort((a, b) => a.order - b.order)[0];
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg overflow-hidden shadow-sm", children: [photo && _jsx("img", { src: photo.url, alt: room.name_ru, className: "w-full h-48 object-cover" }), _jsxs("div", { className: "p-4 flex flex-col gap-3", children: [_jsx("h3", { className: "font-semibold text-gray-900 text-base", children: room.name_ru }), _jsxs("div", { className: "flex flex-col gap-1 text-sm text-gray-600", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u0417\u0430\u0435\u0437\u0434" }), _jsx("span", { className: "font-medium text-gray-800", children: formatDate(searchParams.dfrom) })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u0412\u044B\u0435\u0437\u0434" }), _jsx("span", { className: "font-medium text-gray-800", children: formatDate(searchParams.dto) })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u0413\u043E\u0441\u0442\u0435\u0439" }), _jsx("span", { className: "font-medium text-gray-800", children: searchParams.adults })] })] }), _jsxs("div", { className: "border-t border-gray-100 pt-3", children: [_jsx("p", { className: "text-sm text-gray-600", children: "\u0422\u0430\u0440\u0438\u0444" }), _jsx("p", { className: "text-sm font-medium text-gray-800", children: plan.name_ru ?? plan.name })] }), _jsxs("div", { className: "border-t border-gray-100 pt-3 flex justify-between items-center", children: [_jsx("span", { className: "text-sm text-gray-600", children: "\u0418\u0442\u043E\u0433\u043E" }), _jsxs("span", { className: "text-lg font-bold text-gray-900", children: [plan.price.toLocaleString("ru-RU"), " \u20BD"] })] })] })] }));
}
